testproject/testproject/urls.py
"""2024/11/25 金定歩夢 django移行"""

from django.contrib import admin
from django.urls import path, include
from walkary import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', accounts_views.index, name='index'),
    path('walkary/', include("walkary.urls")),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from walkary import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', accounts_views.index, name='index'),
    path('walkary/', include("walkary.urls")),
]

testproject/walkary/urls.py
from django.urls import path
from django.contrib import admin
from . import views
from django.contrib.auth.views import LogoutView

app_name = "walkary"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create_account, name="create_account"),
    path('login/', views.account_login, name="login"),
    path('logout/', LogoutView.as_view(template_name="walkary/index.html"), name="logout"),
    path("map/", views.mapPage, name="map"),
    path("home/", views.homePage, name="home"),
    path("graph/", views.graphPage, name="graph"),
    path('mypage/', views.myPage, name='mypage'),
    path('logout/', LogoutView.as_view(template_name="walkary/index.html"), name="logout"),
]

walkary/urls.py
"""2024/11/25 金定歩夢 django移行"""
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = "walkary"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create_account, name="create_account"),
    path('login/', views.account_login, name="login"),
    path('logout/', LogoutView.as_view(template_name="walkary/index.html"), name="logout"),
    path("map/", views.mapPage, name="map"),
    path("home/", views.homePage, name="home"),
    path("graph/", views.graphPage, name="graph"),
    path('mypage/', views.myPage, name='mypage'),
    path('logout/', LogoutView.as_view(template_name="walkary/index.html"), name="logout"),
]

testproject/walkary/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    age = models.IntegerField(null=True, blank=True)
    height = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)  # e.g., 170.0 cm
    weight = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)  # e.g., 60.0 kg
    gender = models.CharField(max_length=20, choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他')], blank=True)
    goal = models.IntegerField(null=True, blank=True)  # Step goal

    def __str__(self):
        return f"{self.user.username}'s Profile"

walkary/models.py
"""2024/11/25  django移行"""
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    age = models.IntegerField(null=True, blank=True)
    height = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)
    weight = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他')], blank=True)
    goal = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"


class WalkarySteps(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    steps = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user.username} - {self.date}: {self.steps} steps"

testproject/walkary/forms.py
# walkary/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ("username", "password1", "password2",)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'age', 'height', 'weight', 'gender', 'goal']

walkary/forms.py
"""2024/11/25  django移行"""
# walkary/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        # self.fields['username'].widget.attrs['placeholder'] = 'ユーザーID'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        # self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザーID'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = '確認用パスワード'

    class Meta:
        model = User
        fields = ("username", "password1", "password2",)

class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'placeholder': 'ユーザー名'
        })

    class Meta:
        model = UserProfile
        fields = ['name', 'age', 'height', 'weight', 'gender', 'goal']

testproject/walkary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView
from . forms import UserCreateForm, LoginForm
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import UserProfile
from .forms import UserProfileForm


#indexページ
class Index(TemplateView):
    template_name = 'walkary/index.html'

index = Index.as_view()

#アカウント作成
class Create_Account(View):
    def post(self, request, *args, **kwargs):
        user_form = UserCreateForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # Save the user and profile data
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user  # Link profile to user
            profile.save()

            # Authenticate and login the new user
            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('walkary:mypage')

        return render(request, 'walkary/create.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })

    def get(self, request, *args, **kwargs):
        user_form = UserCreateForm()
        profile_form = UserProfileForm()
        return render(request, 'walkary/create.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })


#ログイン
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('walkary:home')
        return render(request, 'walkary/login.html', {'form': form})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'walkary/login.html', {'form': form})

account_login = Account_login.as_view()


class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class mypageView(View):
    def get(self, request):
        # Get or create the user's profile
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)

        # Load the profile form with existing data
        form = UserProfileForm(instance=user_profile)

        return render(request, "walkary/mypage.html", {
            'form': form,
            'user_profile': user_profile
        })

    def post(self, request):
        # Get the user's profile
        user_profile = get_object_or_404(UserProfile, user=request.user)

        # Update the profile with POST data
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('walkary:mypage')  # Redirect to avoid resubmission on refresh

        return render(request, "walkary/mypage.html", {
            'form': form,
            'user_profile': user_profile
        })


class mapPageView(View):
    def get(self, request):
        return render(request, "walkary/map.html")


@method_decorator(login_required, name='dispatch')
class homePageView(View):
    def get(self, request):
        # Get the user's profile goal if it exists, otherwise set a default
        user_profile = UserProfile.objects.filter(user=request.user).first()
        goal = user_profile.goal if user_profile and user_profile.goal else 5000  # Default to 5000 if no goal set
        return render(request, "walkary/home.html", {"goal": goal})


class graphPageView(View):
    def get(self, request):
        return render(request, "walkary/graph.html")

create_account = Create_Account.as_view()
myPage = mypageView.as_view()
mapPage = mapPageView.as_view()
homePage = homePageView.as_view()
graphPage = graphPageView.as_view()

walkary/views.py
"""2024/11/25 金定歩夢 django移行"""
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView
from .forms import UserCreateForm, LoginForm
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import UserProfile
from .forms import UserProfileForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from datetime import date
from .models import WalkarySteps


#indexページ
class Index(TemplateView):
    template_name = 'walkary/index.html'


#アカウント作成
class Create_Account(View):
    def post(self, request, *args, **kwargs):
        user_form = UserCreateForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('walkary:home')

        return render(request, 'walkary/create.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })

    def get(self, request, *args, **kwargs):
        user_form = UserCreateForm()
        profile_form = UserProfileForm()
        return render(request, 'walkary/create.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })


#ログイン
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('walkary:home')
        return render(request, 'walkary/login.html', {'form': form})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'walkary/login.html', {'form': form})


class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class mypageView(View):
    def get(self, request):
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        form = UserProfileForm(instance=user_profile)
        return render(request, "walkary/mypage.html", {
            'form': form,
            'user_profile': user_profile
        })

    def post(self, request):
        user_profile = get_object_or_404(UserProfile, user=request.user)
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('walkary:mypage')
        return render(request, "walkary/mypage.html", {
            'form': form,
            'user_profile': user_profile
        })


@method_decorator(login_required, name='dispatch')
class mapPageView(View):
    def get(self, request):
        user_profile = UserProfile.objects.filter(user=request.user).first()
        user_height = user_profile.height if user_profile else 170
        return render(request, "walkary/map.html", {"user_height": user_height})


@method_decorator(login_required, name='dispatch')
class homePageView(View):
    def get(self, request):
        user_profile = UserProfile.objects.filter(user=request.user).first()
        goal = user_profile.goal if user_profile and user_profile.goal else 5000
        return render(request, "walkary/home.html", {"goal": goal})


@method_decorator(login_required, name='dispatch')
class graphPageView(View):
    def get(self, request, *args, **kwargs):
        steps_data = WalkarySteps.objects.filter(user=request.user).order_by('date')
        steps_data = [{"date": entry.date.strftime('%Y-%m-%d'), "steps": entry.steps} for entry in steps_data]
        return render(request, 'walkary/graph.html', {'steps_data': json.dumps(steps_data)})


index = Index.as_view()
create_account = Create_Account.as_view()
account_login = Account_login.as_view()
myPage = mypageView.as_view()
mapPage = mapPageView.as_view()
homePage = homePageView.as_view()
graphPage = graphPageView.as_view()

templates/walkary/create.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    {% load static %}
    <link rel="stylesheet" href="{% static 'walkary/css/create.css' %}">
  </head>
  <body>
    <form class="profile-form" method="POST" action="{% url 'walkary:create_account' %}">
      {% csrf_token %}

      <!-- Existing User Fields -->
      <div class="form-section">
        <h3 class="section-title">基本情報</h3>
        <div class="form-group">
          <label class="form-label">ユーザーID</label>
          {{ user_form.username }}
          {{ user_form.username.errors }}
        </div>

        <div class="form-group">
          <label class="form-label">パスワード</label>
          {{ user_form.password1 }}
          {{ user_form.password1.errors }}
          <div class="password-rules">
            ※8文字以上、英数字を含めてください
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">パスワード(確認)</label>
          {{ user_form.password2 }}
          {{ user_form.password2.errors }}
        </div>
      </div>

      <!-- New Profile Fields -->
      <div class="form-section">
        <h3 class="section-title">プロファイル情報</h3>
        <div class="form-group">
          <label class="form-label">名前</label>
          {{ profile_form.name }}
          {{ profile_form.name.errors }}
        </div>
        <button class="submit-btn" type="submit">登録</button>
      </div>

      <div class="form-switch">
        すでにアカウントをお持ちの方は<a href="{% url 'walkary:login' %}">ログイン</a>
      </div>
    </form>
  </body>
</html>

templates/walkary/graph.html
<!DOCTYPE html>
<html lang="ja">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>walkary</title>
    <link rel="stylesheet" href="{% static 'walkary/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'walkary/css/graph.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body class="no-scroll">
    <div class="container">
        <div class="chart-container" style="width: 90%; height: 500px; margin: 20px auto; background: #ffffff; border-radius: 20px; padding: 20px; box-shadow: 0 8px 24px rgba(149, 157, 165, 0.15);">
            <canvas id="stepsChart"></canvas>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'walkary:home' %}"><img src="{% static 'walkary/icons/home.png' %}"alt="ホームアイコン"><br><small>ホーム</small></a></li>
                <li><a href="{% url 'walkary:map' %}"><img src="{% static 'walkary/icons/map.png' %}" alt="マップアイコン"><br><small>マップ</small></a></li>
                <li><a href="{% url 'walkary:graph' %}"class="active"><img src="{% static 'walkary/icons/graph.png' %}" alt="グラフアイコン"><br><small>グラフ</small></a></li>
                <li><a href="{% url 'walkary:mypage' %}"><img src="{% static 'walkary/icons/mypage.png' %}" alt="マイページアイコン"><br><small>マイページ</small></a></li>
            </ul>
        </nav>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const walkedData = JSON.parse(localStorage.getItem('walked_data')) || [];

            // データを日付でソート
            walkedData.sort((a, b) => new Date(a.date) - new Date(b.date));

            // 日付範囲を生成
            const dateRange = [];
            const startDate = new Date(walkedData[0]?.date || new Date().toISOString().split('T')[0]);
            const endDate = new Date(walkedData[walkedData.length - 1]?.date || new Date().toISOString().split('T')[0]);

            for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate() + 1)) {
                dateRange.push(new Date(d).toISOString().split('T')[0]);
            }

            // 日付範囲を元にデータを補完
            const completeData = dateRange.map(date => {
                const existingEntry = walkedData.find(item => item.date === date);
                return existingEntry ? existingEntry : { date: date, steps: 0 };
            });

            // デフォルトで直近7日間のデータを抽出
            const recentData = completeData.slice(-7);

            // 年を除いた日付を作成
            const labels = recentData.map(item => {
                const date = new Date(item.date);
                const month = String(date.getMonth() + 1).padStart(2, '0');
                const day = String(date.getDate()).padStart(2, '0');
                return `${month}/${day}`;
            });

            const steps = recentData.map(item => item.steps);

            // グラフを描画
            const ctx = document.getElementById('stepsChart').getContext('2d');
            
            // グラデーションの作成
            const gradientFill = ctx.createLinearGradient(0, 0, 0, 400);
            gradientFill.addColorStop(0, 'rgba(26, 115, 232, 0.1)');
            gradientFill.addColorStop(1, 'rgba(26, 115, 232, 0.0)');

            const gradientLine = ctx.createLinearGradient(0, 0, 400, 0);
            gradientLine.addColorStop(0, '#1a73e8');
            gradientLine.addColorStop(1, '#6c5ce7');

            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: labels,
                    datasets: [{
                        label: '歩いた距離',
                        data: steps,
                        borderColor: gradientLine,
                        backgroundColor: gradientFill,
                        borderWidth: 3,
                        fill: true,
                        tension: 0.4,
                        pointBackgroundColor: '#ffffff',
                        pointBorderColor: '#1a73e8',
                        pointBorderWidth: 2,
                        pointRadius: 5,
                        pointHoverRadius: 8,
                        pointHoverBackgroundColor: '#ffffff',
                        pointHoverBorderColor: '#6c5ce7',
                        pointHoverBorderWidth: 3,
                        pointShadowOffsetX: 1,
                        pointShadowOffsetY: 1,
                        pointShadowBlur: 5,
                        pointShadowColor: 'rgba(0, 0, 0, 0.1)'
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    layout: {
                        padding: {
                            top: 20,
                            right: 20,
                            bottom: 20,
                            left: 20
                        }
                    },
                    plugins: {
                        legend: {
                            display: true,
                            labels: {
                                font: {
                                    family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
                                    size: 14,
                                    weight: '600'
                                },
                                padding: 20,
                                usePointStyle: true,
                                pointStyle: 'circle',
                                color: '#2c3e50'
                            }
                        },
                        tooltip: {
                            backgroundColor: 'rgba(255, 255, 255, 0.98)',
                            titleColor: '#2c3e50',
                            bodyColor: '#2c3e50',
                            titleFont: {
                                family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
                                size: 14,
                                weight: '600'
                            },
                            bodyFont: {
                                family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
                                size: 14
                            },
                            padding: 12,
                            borderColor: 'rgba(26, 115, 232, 0.1)',
                            borderWidth: 1,
                            displayColors: false,
                            callbacks: {
                                label: function(context) {
                                    return `${context.parsed.y.toLocaleString()} m`;
                                }
                            },
                            cornerRadius: 8,
                            caretSize: 6,
                            boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
                        }
                    },
                    scales: {
                        y: {
                            beginAtZero: true,
                            grid: {
                                color: 'rgba(0, 0, 0, 0.05)',
                                drawBorder: false,
                                lineWidth: 1
                            },
                            border: {
                                display: false
                            },
                            ticks: {
                                font: {
                                    family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
                                    size: 12,
                                    weight: '500'
                                },
                                padding: 10,
                                color: '#2c3e50',
                                callback: function(value) {
                                    return value.toLocaleString() + ' m';
                                }
                            },
                            title: {
                                display: true,
                                text: '歩いた距離',
                                font: {
                                    family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
                                    size: 14,
                                    weight: '600'
                                },
                                padding: {top: 10, bottom: 10},
                                color: '#2c3e50'
                            }
                        },
                        x: {
                            grid: {
                                display: false
                            },
                            border: {
                                display: false
                            },
                            ticks: {
                                font: {
                                    family: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
                                    size: 12,
                                    weight: '500'
                                },
                                padding: 10,
                                color: '#2c3e50'
                            }
                        }
                    },
                    interaction: {
                        intersect: false,
                        mode: 'index'
                    },
                    animation: {
                        duration: 1000,
                        easing: 'easeInOutQuart'
                    },
                    elements: {
                        line: {
                            tension: 0.4,
                            borderWidth: 3,
                            borderJoinStyle: 'round',
                            capBezierPoints: true
                        }
                    }
                }
            });
        });
    </script>
</body>
</html>

templates/walkary/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="{% static 'walkary/css/index.css' %}">
    <title>Walkary - ホーム</title>
  </head>
  <body>
    <header>
      <h1>Walkary</h1>
    </header>

    <main>
      <div class="card-grid">
        {% if user.is_authenticated %}
          <div class="card welcome-card">
            <h2>ようこそ、{{ user.username }}さん</h2>
            <p>本日の歩数を記録しましょう！</p>
            <div class="button-container">
              <a href="{% url 'walkary:home' %}" class="button">ホーム</a>
              <form method="post" action="{% url 'walkary:logout' %}" class="logout-form">
                {% csrf_token %}
                <button type="submit" class="button">ログアウト</button>
              </form>
            </div>
          </div>
        {% else %}
          <div class="card auth-card">
            <h2>ログイン</h2>
            <div class="auth-container">
              <a href="{% url 'walkary:login' %}" class="button">ログイン</a>
              <a href="{% url 'walkary:create_account' %}" class="button">新規登録</a>
            </div>
          </div>
        {% endif %}
      </div>
    </main>
  </body>
</html>

templates/walkary/mypage.html
<!DOCTYPE html>
<html lang="ja">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>walkary</title>
    <link rel="stylesheet" href="{% static 'walkary/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'walkary/css/mypage.css' %}">
</head>
<body>
    <div class="container">
        <form method="post" action="{% url 'walkary:logout' %}" id="logout-form">
            {% csrf_token %}
            <button type="submit">ログアウト</button>
        <!-- <img src="{% static 'walkary/icons/logout.png' %}" alt="ログアウトアイコン" style="width:16px; height:16px;">-->  
        </form>
        <main>
            <section>
                <h2>ユーザー情報</h2>
            </section>
            <div id="info">
                <p>名前：{{ user_profile.name }}</p>
                <p>年齢：{{ user_profile.age }}</p>
                <p>身長：{{ user_profile.height }} cm</p>
                <p>体重：{{ user_profile.weight }} kg</p>
                <p>性別：{{ user_profile.gender }}</p>
                <p>目標：{{ user_profile.goal }}m</p>
            </div>

            <button id="edit-button" onclick="toggleForm()">変更</button>

            <div id="form" class="hidden">
                <form method="post" action="{% url 'walkary:mypage' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
            <button type="submit">保存</button>
                </form>
            </div>
        </main>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                const userHeight = {{ user_profile.height }};
                localStorage.setItem('userHeight', userHeight);
                const userWeight = {{ user_profile.weight }};
                localStorage.setItem('userWeight', userWeight);
            });
        </script>
        <nav>
            <ul>
                <li><a href="{% url 'walkary:home' %}" ><img src="{% static 'walkary/icons/home.png' %}"alt="ホームアイコン"><br><small>ホーム</small></a></li>
                <li><a href="{% url 'walkary:map' %}"><img src="{% static 'walkary/icons/map.png' %}" alt="マップアイコン"><br><small>マップ</small></a></li>
                <li><a href="{% url 'walkary:graph' %}"><img src="{% static 'walkary/icons/graph.png' %}" alt="グラフアイコン"><br><small>グラフ</small></a></li>
                <li><a href="{% url 'walkary:mypage' %}" class="active"><img src="{% static 'walkary/icons/mypage.png' %}" alt="マイページアイコン"><br><small>マイページ</small></a></li>
            </ul>
        </nav>

    </div>

    <script>
        function toggleForm() {
            var form = document.getElementById("form");
            form.classList.toggle("show");
        }
    </script>
</body>
</html>